### ISSUE TITLE
Switch from `Extradata` to `Signer` in standard header to secure authority engine

### ISSUE THREAD

**Issue by blazejkrzak** [lukso-network/go-ethereum#18]
As a developer
I want to have working aura engine based on headers
So I should adjust previous code to recent changes

**Comment by blazejkrzak** [comment]
What is the current status of this?

**Comment by mxmar** [comment]
- block `data` from database (from Ancient db after second try - after background freezer operation) contains inproper struct:
```
	if len(data) > 0 && crypto.Keccak256Hash(data) == hash {
		return data
	}
```
`rypto.Keccak256Hash(data) == hash` did not match (starting from block `#1` and higher)
- @patred20 has prepared `EncodeToBytes` with `encodeSigHeader` struct to change existing `data` for debug purpose and after that we're getting proper blocks data (file: `core/rawdb/accessors_chain.go:302`)
- on the upper level (`core/rawdb/accessors_chain.go:339`) the `rlp.Decode(bytes.NewReader(data), header)` can't decode affected by @patred20 `data` because of `header := new(types.Header)` - next step should be to use `AuraHeader` there - @patred20 you should confirm that changing struct will resolve te `rlp.Decode` issue there (it should but make sure that is as first of all)
